substitutions:
  device_name: ""
  friendly_name: ""

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name} 

esp8266:
  board: esp01_1m

# Enable logging
logger:
  level: DEBUG 

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key 

ota:
  - platform: esphome
    password: !secret ota_password 

wifi:
  ssid: !secret wifi_ssid
  # password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${device_name} 
    password: !secret ap_password

captive_portal:

binary_sensor:
  - platform: status
    name: ${device_name}

remote_receiver:
  id: rcvr
  pin:
    number: GPIO14
    inverted: true
    mode:
      input: true
      pullup: true
  tolerance: 60%
  # dump: raw

remote_transmitter:
  id: transmitter
  pin: GPIO4
  carrier_duty_percent: 50%

sensor:
  - platform: wifi_signal
    name: "WiFi Strength"
    update_interval: 300s
  - platform: uptime
    name: "Uptime"


### Custom components
# external_components:
#   - source:
#       type: git
#       url: https://github.com/nayot/esphome_ir_custom_components
#       path: custom_components
#       ref: main
#     components: [ carrier_ac ]
external_components:
  - source: ./custom_components
    components: [ carrier_ac ]

climate:
  - platform: carrier_ac
    name: ${device_name} 
    transmitter_id: transmitter
    receiver_id: rcvr
