esphome:
  name: test-node
  friendly_name: "Test A/C Node"

esp8266:
  board: esp01_1m

logger:
  level: DEBUG

api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password
wifi:
  ssid: !secret wifi_ssid
  ap:
    ssid: "Test A/C Node"
    password: !secret ap_password

captive_portal:

binary_sensor:
  - platform: status
    name: "Test Node A/C Connected"

remote_receiver:
  id: rcvr
  pin:
    number: GPIO14
    inverted: true
    mode:
      input: true
      pullup: true
  tolerance: 60%
  dump: raw

remote_transmitter:
  id: transmitter
  pin: GPIO4
  carrier_duty_percent: 50%

sensor:
  - platform: wifi_signal
    name: "WiFi Strength"
    update_interval: 300s
  - platform: uptime
    name: "Uptime"


### Custom components
external_components:
  - source: ./custom_components
    components: [ carrier_ac ]

climate:
  - platform: carrier_ac
    name: "Test Node A/C"
    transmitter_id: transmitter
    # receiver_id: rcvr

    